TARGET_ARCH = hpux11

CC     = aCC
OPT    = +O1
DEBUG  = -g
OTHER  = -Aa -ext +DA2.0 +DS2.0
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = display.cpp numgen.cpp main.cpp stage1.cpp stage2.cpp stage3.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
