TARGET_ARCH = linux

CC = g++
OPT    = -O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) -fexceptions -Wall

MODULE = run
SRCS = stimulus.cpp display.cpp fir.cpp main.cpp
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs

