TARGET_ARCH = hpux11

CC     = aCC
OPT    = +O1
DEBUG  = -g
OTHER  = -Aa +DA2.0 +DS2.0
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = demo.cpp sc_thread_pool.cpp
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
