TARGET_ARCH = sparcOS5

CC     = CC
OPT    = -O3
DEBUG  = -g
OTHER  =
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = simple_fifo.cpp
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs

clean::
	rm -rf SunWS_cache
