TARGET_ARCH = hpux10

CC = aCC
OPT    = +O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) +DAportable +p

MODULE = demo
SRCS = paging.cpp icache.cpp mmxu.cpp pic.cpp floating.cpp dcache.cpp fetch.cpp bios.cpp exec.cpp decode.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs 
