TARGET_ARCH = sparcOS5

CC = CC
OPT    = -O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) -pto

MODULE = demo
SRCS = paging.cpp icache.cpp mmxu.cpp pic.cpp floating.cpp dcache.cpp fetch.cpp bios.cpp exec.cpp decode.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
