TARGET_ARCH = hpux10

CC = aCC
OPT    = +O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) +DAportable +p

MODULE = run
SRCS = fifo.cpp sender.cpp switch_clk.cpp switch.cpp receiver.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
