TARGET_ARCH = sparcOS5

CC     = CC
OPT    = -O3
DEBUG  = -g
OTHER  =
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = fifo.cpp sender.cpp switch_clk.cpp switch.cpp receiver.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs

clean::
	rm -rf SunWS_cache
