TARGET_ARCH = gccsparcOS5

CC     = g++
OPT    = -O3
DEBUG  = -g
OTHER  = -Wall
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = fifo.cpp sender.cpp switch_clk.cpp switch.cpp receiver.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
