TARGET_ARCH = hpux11

CC     = aCC
OPT    = +O1
DEBUG  = -g
OTHER  = -Aa -ext +DA2.0 +DS2.0
CFLAGS = $(OPT) $(OTHER)
# CFLAGS = $(DEBUG) $(OTHER)

MODULE = simple_bus

include Makefile.srcs

OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs 
