TARGET_ARCH = hpux11

CC     = aCC
OPT    = +O1
DEBUG  = -g
OTHER  = -Aa +DA2.0 +DS2.0
# CFLAGS = $(OPT) $(OTHER)
CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = paging.cpp icache.cpp mmxu.cpp pic.cpp floating.cpp dcache.cpp fetch.cpp bios.cpp exec.cpp decode.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs 
