TARGET_ARCH = linux

CC     = g++
OPT    = -O3
DEBUG  = -g
OTHER  = -Wall
# CFLAGS = $(OPT) $(OTHER)
CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = paging.cpp icache.cpp mmxu.cpp pic.cpp floating.cpp dcache.cpp fetch.cpp bios.cpp exec.cpp decode.cpp main.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
