TARGET_ARCH = hpux10

CC = aCC
OPT    = +O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) +DAportable +p


MODULE = run
SRCS = display.cpp numgen.cpp main.cpp stage1.cpp stage2.cpp stage3.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
