TARGET_ARCH = sparcOS5

CC = CC
OPT    = -O3
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) -pto


MODULE = run
SRCS = display.cpp numgen.cpp main.cpp stage1.cpp stage2.cpp stage3.cpp 
OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
